---
version: "3.8"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8088:80"
      - "8443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - laravel-php
      - mysql
      - redis
    networks:
      - laravel

  # mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - db-livewire:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    container_name: mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    ports:
      - "6379:6379"
    networks:
      - laravel


  laravel-php:
    image: laravel-php
    build:
      context: ./
      dockerfile: Dockerfile-php
      args:
        - APP_ENV=${APP_ENV}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: laravel-php
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
      - "5173:5173"
    networks:
      - laravel

  laravel-queue:
    restart: always
    image: laravel-php
    depends_on:
      - laravel-php
    container_name: laravel-queue
    command: php /var/www/html/artisan queue:work
    depends_on:
      - redis
    volumes:
      - ./src:/var/www/html/
    networks:
      - laravel

  laravel-crontab:
    build:
      context: ./
      dockerfile: Dockerfile-cron
      args:
        - APP_ENV=${APP_ENV}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: laravel-crontab
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

volumes:
  db-livewire: ~
